language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules

script:
  - yarn lint
  - yarn stylelint
  - yarn test:cover
  - yarn compileConf:dev
  - yarn prod

deploy:
  provider: pages
  local_dir: dist
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master

notifications:
  email: false